import random
import numpy as np
import matplotlib.pyplot as plt
x0 = random.choices(np.arange(0, 6, 0.01), k = 150) 
y0 = random.choices(range(8000), k =150)
x1 = random.choices(np.arange(0.1, 0.8, 0.01), k = 150) 
y1 = random.choices(range(1000, 8000), k = 150)
x2 = random.choices(np.arange(0.45, 0.85, 0.01), k = 150) 
y2 = random.choices(range(1000, 9000), k = 150) 
x3 = random.choices(np.arange(0.2, 0.8, 0.01), k = 150) 
y3 = random.choices(range(8500), k = 150)
plt.suptitle('Bike Rentals at Different Temperature By Season', fontweight = 'bold')
plt.subplot(2, 2, 1)
plt.scatter(x0, y0 , color = 'green', marker = '.')
plt.title('Spring', color = 'green', fontweight = 'bold')
plt.subplot(2, 2, 2)
plt.scatter(x1, y1 , color = 'yellow',  marker = '.')
plt.title('Summer',  color = 'yellow', fontweight = 'bold')
plt.subplot(2, 2, 3)
plt.scatter(x2, y2 , color = 'red',  marker = '.')
plt.title('Fall or Autumn',  color = 'red', fontweight = 'bold')
plt.subplot(2, 2, 4)
plt.scatter(x3, y3 , color = 'blue',  marker = '.')
plt.title('Winter',  color = 'blue', fontweight = 'bold')
plt.show()